export default interface EditQuestionProps{
    error: boolean,
    tag_name: string[],
    book_name: string,
    title: string,
    answer: string,
    lang: string,
    chapter_number?: number,
    verse_number: string,
    verse_context: string,
    startTagname: any,
    startQuestion: any,
    startAnswer: any,
    startReference: any,
    startAddBibleverse: any,
    startPostAddBibleverse: any,
    questiondetails: any,
    biblelist: any,
    init_tag_name: any
}